#include "catch.hpp"
#include "sp/sp.h"
#include "pkb/EntityManager.h"
#include "pkb/QueryPKB.h"
#include "sp/tokenizer/IntegerToken.h"
#include "sp/tokenizer/ArithmeticToken.h"
#include "sp/tokenizer/NameToken.h"
#include "sp/tokenizer/PunctuationToken.h"
#include "sp/parser/ExpressionParserFactory.h"
#include "sp/parser/IfStatementParser.h"

