name: clang-format Check
on: [pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: macos-latest
    strategy:
      matrix:
        path:
          - './Team03/Code03/src/spa'
          - './Team03/Code03/src/unit_testing'
          - './Team03/Code03/src/integration_testing'
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '13'
          check-path: ${{ matrix.path }}
