name: build & test
on: [ pull_request ]
jobs:
  build-project:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Configure the project
        uses: threeal/cmake-action@v1.3.0
        with:
          source-dir: "./Team03/Code03/"
          run-build: true
          generator: Ninja
          c-compiler: cc
          cxx-compiler: c++

      - name: Build the project
        run: cmake --build ./Team03/Code03/build --config Release --target all -- -j 14

      - name: Run unit tests
        run: ./Team03/Code03/build/src/unit_testing/unit_testing

      - name: Run integration tests
        run: ./Team03/Code03/build/src/integration_testing/integration_testing

      - name: Run Autotester for Multiple Test Files
        run: |
          for source_file in *_source.txt; do
            base_name="${source_file##*/}"
            base_name="${base_name%_source.txt}"  
            echo "Base Name: $base_name"
            query_file="${base_name}_queries.txt"
            echo "Query File: $query_file"
            cd ../Code03/build/src/autotester
            ./autotester "../../../../Tests03/$source_file" "../../../../Tests03/$query_file" "../../../../Tests03/"$base_name"_out.xml" > ""$base_name"_autotester_output_file.txt"
            ls -l ../../../../Tests03
          
            autotester_exit_status=$?
            if [ $autotester_exit_status -eq 0 ]; then
              echo "Autotester ran successfully for $base_name."
            else
              echo "Autotester failed for $base_name."
              exit 1  # Fail the CI pipeline if Autotester fails
            fi
               
            autotester_output=$(cat ""$base_name"_autotester_output_file.txt")
            if echo "$autotester_output" | grep -q -i "Missing\|Additional\|TIMEOUT"; then
              echo "Missing or Additional or TIMEOUT found for $base_name: $autotester_output"
              export AUTOTESTER_RESULT=fail
              exit 1  # This will cause the workflow to fail
            else
              echo "No Missing or Additional found for $base_name."
              export AUTOTESTER_RESULT=pass
            fi
            if [ -f "../../../../Tests03/$base_name"_out.xml"" ]; then
              cp "../../../../Tests03/"$base_name"_out.xml" "$GITHUB_WORKSPACE/"$base_name"_out.xml"
            fi        
          
          cd ../../../../Tests03
          done
        working-directory: ./Team03/Tests03/

      - name: Create and Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: XML files generated by Autotester
          path: ./*_out.xml